import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion,MotionConfig,useReducedMotion} from 'framer-motion';
import gsap from 'gsap';
import {NebulaEntrance} from './components/ui/nebula-entrance';
import {HowItWorks} from './components/ui/how-it-works';

const names={ibm_rx:'IBM rotation',guppy_v3:'Guppy V3',gearbox:'Gearbox',upload:'Your circuit'};
const policies={repaired_source:'Repaired source',fixed_retry:'Fixed retry',selected_retry:'Selected retry',deterministic:'Deterministic'};
const policyNotes={repaired_source:'Retain the trial. Recover every failure.',fixed_retry:'A conservative retry cap.',selected_retry:'A cap selected from success probability.',deterministic:'Implement the target directly.'};
const defaults={example:'ibm_rx',timeout:'0.01',max_attempts:'16',require_source:false,cx:'10',one_qubit:'1',measure:'5',reset:'5'};
const fmt=n=>typeof n==='number'?(n===0?'0':n<.0001?n.toExponential(2):Number(n.toPrecision(5)).toString()):'—';
const pct=n=>typeof n==='number'?fmt(n*100)+'%':'—';
function Icon({name='arrow',size=18,...props}){const paths={arrow:'M4 12h15m-6-6 6 6-6 6',down:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',check:'m5 12 4 4L19 6',plus:'M12 5v14M5 12h14',x:'m6 6 12 12M18 6 6 18',file:'M14 2H5v20h14V7zM14 2v6h5M8 12h8M8 16h6',play:'m8 4 12 8-12 8z',orbit:'M21 12a9 9 0 1 1-9-9M9 3h3v3M6 12h12M12 7v10',settings:'M4 7h16M4 17h16M8 4v6M16 14v6'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d={paths[name]||paths.arrow}/></svg>}
function Tag({children,tone=''}){return <span className={'tag '+tone}><span className="tag-dot"/>{children}</span>}
function AnimatedButton({children,className='',still,...props}){return <motion.button {...props} className={className} whileHover={still?{}:{y:-2}} whileTap={still?{}:{scale:.985}}>{children}</motion.button>}
async function getJSON(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data}
function FileSlot({label,accept,file,setFile}){return <label className={'file-slot '+(file?'loaded':'')}><Icon name="file"/><span><b>{file?file.name:label}</b><small>{file?'Click to replace':accept+' · Select file'}</small></span><Icon name="plus" size={15}/><input type="file" aria-label={label} accept={accept} onChange={e=>setFile(e.target.files[0]||null)}/></label>}

function Diagnosis({diagnosis,comparison,still}){
 const [selected,setSelected]=useState(null);const branches=diagnosis?.branches||[];const active=branches.find(b=>b.syndrome===selected)||branches.find(b=>b.status==='violated')||branches[0];
 const source=comparison?.candidates.find(c=>c.policy==='repaired_source');
 if(!active)return <div className="empty-inner">No branch diagnosis is available for this input.</div>;
 const witness=active.affected_state;
 return <><div className="section-intro"><div><div className="eyebrow">ORIGINAL TRIAL / BEFORE RECOVERY</div><h3>Follow the failure.</h3></div><p>Inspect what each outcome does to your data.</p></div>
 <div className="branch-map"><div className="trial-chip"><Icon name="orbit"/>Original trial</div><div className="branch-stem"/><div className="branch-options">{branches.map(b=><button key={b.syndrome} className={'branch-node '+(active.syndrome===b.syndrome?'selected ':'')+(b.status==='violated'?'attention':'')} onClick={()=>setSelected(b.syndrome)} aria-pressed={active.syndrome===b.syndrome}><span className="mono">{b.bits}</span><span>{b.syndrome===0?'Success branch':'Failure branch'}</span><small>{b.probability===null?'Input-dependent':pct(b.probability)}</small></button>)}</div></div>
 <AnimatePresence mode="wait"><motion.div key={active.syndrome} initial={{opacity:0,y:still?0:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:still?0:-5}} transition={{duration:still?0:.2}} className="branch-detail"><div className="detail-heading"><span className="mono">OUTCOME {active.bits}</span><Tag tone={active.status==='violated'?'amber':active.status==='satisfied'?'green':''}>{active.status==='violated'?'Contract violation':active.status==='satisfied'?'Contract satisfied':'Below tolerance'}</Tag></div><h4>{active.syndrome===0?'Does success apply the intended operation?':'Does failure preserve the input?'}</h4><p>{active.explanation}</p>
 {active.proposed_correction&&<div className="correction"><Icon name="arrow"/><div><span className="eyebrow">PROPOSED CORRECTION</span><p>{active.proposed_correction.instruction}</p></div></div>}
 {witness&&<details className="witness"><summary>See an affected input <Icon name="plus" size={15}/></summary><p className="muted">Input: {witness.input_state} · Measurement: {witness.measurement_basis} · Probability of the + outcome</p><div className="witness-bars">{[['Expected',witness.expected_plus_probability,'expected'],['Original branch',witness.actual_plus_probability,'original'],...(typeof witness.corrected_plus_probability==='number'?[['After proposed correction',witness.corrected_plus_probability,'corrected']]:[])].map(([label,v,kind])=><div className="witness-row" key={label}><span>{label}</span><div><motion.i initial={{width:0}} animate={{width:`${Math.max(0,Math.min(100,v*100))}%`}} transition={{duration:still?0:.5}} className={kind}/></div><b>{pct(v)}</b></div>)}</div><p className="fine">An illustrative state calculation from the diagnosis. Full exported-circuit verification is shown separately below.</p></details>}
 </motion.div></AnimatePresence>
 <div className={'verification-strip '+(source?.verified?'passed':'')}><Icon name={source?.verified?'check':'orbit'}/><div><strong>{source?.verified?'Generated source repair passed both engines':source?.unavailable_reasons?'Source repair unavailable under this budget':'Exported source repair not verified'}</strong><p>{source?.verified?'Success applies the target. Timeout preserves the input.':source?.unavailable_reasons?.join(' ')||'A proposed correction alone is not an accepted implementation.'}</p></div>{source?.verified&&<span className="mono">CAP {source.cap}</span>}</div><p className="fine">{diagnosis.source_caveat}</p></>
}
function Compare({comparison,runId,downloads,still}){
 const [detail,setDetail]=useState(null);const max=Math.max(1,...comparison.candidates.map(c=>c.weighted_expected_cost||0));
 return <><div className="section-intro"><div><div className="eyebrow">SAME CONTRACT / FOUR ALTERNATIVES</div><h3>Choose with evidence.</h3></div><p>Expected cost per invocation.<br/>Lower is better within this model.</p></div><div className="candidate-list">{comparison.candidates.map(c=><div key={c.policy} className={'candidate '+(comparison.recommendation.policy===c.policy?'winner':'')}><div className="candidate-top"><div><h4>{policies[c.policy]}</h4><p>{policyNotes[c.policy]}</p></div><strong>{fmt(c.weighted_expected_cost)}<small>cost score</small></strong></div><div className="cost-track"><motion.div initial={{width:0}} animate={{width:`${100*(c.weighted_expected_cost||0)/max}%`}} transition={{duration:still?0:.8,ease:'easeOut'}}/></div><div className="candidate-facts"><span>Timeout <b>{pct(c.timeout_probability)}</b></span><span>Cap <b>{c.cap??'—'}</b></span><span>{c.preserves_source?'Retains original trial':'Direct replacement'}</span><Tag tone={c.verified?'green':c.unavailable_reasons?'':'red'}>{c.verified?'Both engines passed':c.unavailable_reasons?'Unavailable':'Verification failed'}</Tag></div><div className="candidate-bottom"><span>{comparison.recommendation.policy===c.policy?'↗ Recommended':c.eligible?'Eligible':c.exclusion_reasons.join(' ')}</span><button className="text-button" onClick={()=>setDetail(detail===c.policy?null:c.policy)} aria-expanded={detail===c.policy}>{detail===c.policy?'Hide evidence':'Inspect'} <Icon name="plus" size={14}/></button></div>{detail===c.policy&&<pre>{JSON.stringify(c,null,2)}</pre>}{downloads.includes('circuits/'+c.qasm_file)&&<a className="circuit-link" href={'/api/runs/'+runId+'/circuits/'+c.qasm_file} download={c.qasm_file}><Icon name="down" size={14}/> Download verified QASM</a>}</div>)}</div><div className="model-note"><Icon name="settings"/><p>{comparison.cost_model.units} Classical control, idle time and hardware noise are excluded. Static counts are not executed worst-case paths.</p></div></>
}
function App(){
 const [entered,setEntered]=useState(location.hash==='#workspace');
 useEffect(()=>{const sync=()=>{setEntered(location.hash==='#workspace');window.scrollTo(0,0)};window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 const reduced=useReducedMotion();const [motionOff,setMotionOff]=useState(false);const still=Boolean(reduced)||motionOff;
 const [form,setForm]=useState(defaults),[manifest,setManifest]=useState(null),[qasm,setQasm]=useState(null),[advanced,setAdvanced]=useState(false);
 const [state,setState]=useState(null),[busy,setBusy]=useState(false),[stale,setStale]=useState(false),[clientError,setClientError]=useState(''),[runId,setRunId]=useState(''),[tab,setTab]=useState('diagnose'),[info,setInfo]=useState(false);
 const revision=useRef(0),token=useRef(''),alive=useRef(true),page=useRef(null);useEffect(()=>()=>{alive.current=false},[]);
 useEffect(()=>{if(still||!entered)return;const ctx=gsap.context(()=>{gsap.from('.hero-word',{yPercent:108,opacity:0,duration:1.05,stagger:.11,ease:'power4.out'});gsap.from('.hero-sub',{y:16,opacity:0,duration:.9,delay:.25});gsap.from('.topbar',{y:-12,opacity:0,duration:.7})},page);return()=>ctx.revert()},[still,entered]);
 function invalidate(){revision.current++;setState(null);setRunId('');setStale(true);setClientError('')}
 function update(key,value){invalidate();setForm(f=>({...f,[key]:value}))}
 async function execute(event){event?.preventDefault();if(busy)return;const rev=revision.current;setBusy(true);setStale(false);setClientError('');setState({status:'running',stage:'load'});setRunId('');setTab('diagnose');try{if(!token.current)token.current=(await getJSON('/api/config')).token;const request={example:form.example,timeout:Number(form.timeout),max_attempts:Number(form.max_attempts),require_source:form.require_source,weights:Object.fromEntries(['cx','one_qubit','measure','reset'].map(k=>[k,Number(form[k])]))};if(form.example==='upload'){if(!manifest||!qasm)throw Error('Select a manifest and a QASM file.');if(manifest.size>50000||qasm.size>200000)throw Error('Use a manifest under 50 KB and QASM under 200 KB.');request.manifest=JSON.parse(await manifest.text());request.qasm=await qasm.text()}const id=(await getJSON('/api/runs',{method:'POST',headers:{'Content-Type':'application/json','X-RetryGuard-Token':token.current},body:JSON.stringify(request)})).run_id;let failures=0;for(;;){if(!alive.current)break;let next;try{next=await getJSON('/api/runs/'+id);failures=0}catch(e){failures++;if(failures>=3)throw e;await new Promise(r=>setTimeout(r,1000));continue}if(rev===revision.current){setState(next);setRunId(id)}if(next.status!=='running')break;await new Promise(r=>setTimeout(r,450))}}catch(e){if(rev===revision.current){setClientError(e.message);setState(null)}}finally{if(alive.current)setBusy(false)}}
 const comparison=state?.report?.comparison,diagnosis=state?.diagnosis,recommendation=comparison?.recommendation,downloads=state?.downloads||[];
 const status=clientError?'failed':state?.status||'idle';const isDone=status==='complete';const failed=status==='failed'||status==='rejected';
 const statusLabel=stale?'Inputs changed':clientError?'Request failed':status==='running'?state?.stage==='load'?'Validating input':state?.stage==='diagnose'?'Reading the branches':'Generating & checking':isDone?'Execution complete':status==='rejected'?'Input rejected':status==='failed'?'Execution failed':'Ready when you are';
 const headline=stale?'Run again for this configuration.':clientError||state?.error?.message|| (isDone?'The results are in.':busy?'Working through every outcome.':'Your next move starts here.');
 const count= comparison?.candidates.filter(c=>c.verified).length;
 const stages=[{name:'Load',done:!!diagnosis||isDone,active:status==='running'&&state?.stage==='load'},{name:'Diagnose',done:!!diagnosis,active:status==='running'&&state?.stage==='diagnose'},{name:'Repair',done:!!comparison,active:status==='running'&&state?.stage==='repair_verify_compare'},{name:'Verify',done:!!comparison,active:status==='running'&&state?.stage==='repair_verify_compare'},{name:'Compare',done:!!comparison,active:status==='running'&&state?.stage==='repair_verify_compare'},{name:'Download',done:false,active:isDone}];
 return <MotionConfig reducedMotion={still?'always':'user'}><div ref={page} className={still?'app still':'app'}>{!entered?<NebulaEntrance onEnter={()=>{location.hash='workspace'}} onHowItWorks={()=>setInfo(true)}/>:<><a className="skip" href="#workspace">Skip to workspace</a><header className="topbar"><a className="brand" href="#"><span className="brand-symbol"><i/><i/></span>RetryGuard<span className="brand-mark">/</span></a><nav aria-label="Main navigation"><a className="active" href="#workspace">Workspace</a><button onClick={()=>setInfo(true)}>How it works <span>↗</span></button></nav><div className="header-right"><span className="local-label"><i/>LOCAL EXECUTION</span><button className="motion-switch" onClick={()=>setMotionOff(!motionOff)} aria-pressed={still} aria-label={still?'Enable motion':'Pause motion'}><span className="wave">∿</span>{still?'Motion off':'Motion on'}</button></div></header>
 <main>
 <section className="workspace" id="workspace"><div className="workspace-heading"><div><span className="eyebrow">THE EXECUTION WORKSPACE</span><h2>Make the next move.</h2></div><div className="mode-control"><button className={!advanced?'selected':''} onClick={()=>setAdvanced(false)}>Guided</button><button className={advanced?'selected':''} onClick={()=>setAdvanced(true)}>Expert</button></div></div>
 <div className="work-grid"><aside className="config-panel"><div className="panel-top"><span className="mono">01 / INPUT</span><Icon name="settings" size={17}/></div><form onSubmit={execute}><label htmlFor="example">Start with a circuit</label><div className="select-wrap"><select id="example" value={form.example} onChange={e=>update('example',e.target.value)}><option value="ibm_rx">IBM rotation</option><option value="guppy_v3">Guppy V3</option><option value="gearbox">Gearbox</option><option value="upload">Upload your routine</option></select><span>⌄</span></div><p className="field-note">{form.example==='upload'?'Bring one manifest and its gate-only trial.':'A source-backed example. Results appear only after execution.'}</p>
 <AnimatePresence initial={false}>{form.example==='upload'&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} transition={{duration:still?0:.25}} className="upload-zone"><FileSlot label="Manifest JSON" accept=".json" file={manifest} setFile={f=>{invalidate();setManifest(f)}}/><FileSlot label="Trial QASM" accept=".qasm,.txt" file={qasm} setFile={f=>{invalidate();setQasm(f)}}/></motion.div>}</AnimatePresence>
 <div className="divider"/><div className="input-pair"><div><label htmlFor="timeout">Timeout limit</label><input id="timeout" type="number" min="0" max="1" step="any" required value={form.timeout} onChange={e=>update('timeout',e.target.value)}/><small>{form.timeout!==''&&Number.isFinite(Number(form.timeout))?pct(Number(form.timeout))+' probability':'Enter a probability'}</small></div><div><label htmlFor="cap">Attempt cap</label><input id="cap" type="number" min="1" max="32" step="1" required value={form.max_attempts} onChange={e=>update('max_attempts',e.target.value)}/><small>1–32 attempts</small></div></div>
 <label className="switch-row"><div><span>Preserve original trial</span><small>Exclude direct replacements</small></div><input type="checkbox" checked={form.require_source} onChange={e=>update('require_source',e.target.checked)}/><span className="switch-visual"/></label>
 <details className="cost-settings" open={advanced} onToggle={e=>{if(e.target.open!==advanced)setAdvanced(e.target.open)}}><summary>Cost assumptions <Icon name="plus" size={16}/></summary><p className="field-note">Dimensionless weights, not measured hardware costs.</p><div className="cost-inputs">{[['cx','CX'],['one_qubit','One-qubit'],['measure','Measure'],['reset','Reset']].map(([key,label])=><div key={key}><label htmlFor={key}>{label}</label><input id={key} type="number" min="0" step="any" required value={form[key]} onChange={e=>update(key,e.target.value)}/></div>)}</div></details>
 <AnimatedButton still={still} className="run-button" disabled={busy} type="submit"><span>{busy?'Execution in progress':'Run analysis'}</span><Icon name={busy?'orbit':'arrow'}/></AnimatedButton><p className="execution-note"><i className={busy?'busy-dot':''}/> {busy?'One execution at a time':'Runs locally. No precomputed scores.'}</p></form><div className="supported"><span className="mono">SUPPORTED CLASS</span><p>1 data qubit · 1–2 ancillas<br/>Gate-only OpenQASM 3 trial</p><button onClick={()=>setInfo(true)}>View model & limits <Icon name="arrow" size={13}/></button></div></aside>
 <div className="execution-panel"><div className="pipeline" aria-label="Execution stages">{stages.map((s,i)=><div className={(s.done?'done ':'')+(s.active?'current':'')} key={s.name}><span className="stage-circle">{s.done?<Icon name="check" size={12}/>:String(i+1).padStart(2,'0')}</span><span>{s.name}</span></div>)}</div>
 <div className={'execution-status '+(failed?'error':'')} role="status" aria-live="polite"><Tag tone={isDone?'green':failed?'red':busy?'blue':''}>{statusLabel}</Tag><h3>{headline}</h3><p>{stale?(busy?'The old execution will finish, but its results will not be displayed.':'Previous results have been cleared.'):failed?(state?.error?.code||'Check the input or local server and try again.'):isDone?'Every displayed result below comes from this execution.':busy?'Generation and verification share a stage. No passes are shown until checks return.':'Load → diagnose → repair → verify → compare → download.'}</p></div>
 {recommendation&&<motion.div className="recommendation" initial={{opacity:0,y:still?0:16}} animate={{opacity:1,y:0}}><div className="recommendation-header"><span className="eyebrow">{recommendation.policy?'RECOMMENDED IMPLEMENTATION':'NO ELIGIBLE IMPLEMENTATION'}</span><span className="recommendation-arrow">↗</span></div><h3>{policies[recommendation.policy]||'Revisit the constraints.'}</h3><p>{recommendation.reason}</p><div className="recommendation-stats"><div><small>EXPECTED COST</small><b>{fmt(recommendation.weighted_expected_cost)}<em> score</em></b></div><div><small>TIMEOUT</small><b>{pct(comparison.candidates.find(c=>c.policy===recommendation.policy)?.timeout_probability)}</b></div><div><small>VERIFIED OPTIONS</small><b>{count}<em> / 4</em></b></div></div></motion.div>}
 {diagnosis?<div className="results-area"><div className="result-tabs" role="tablist" aria-label="Execution results">{[['diagnose','Branch diagnosis'],['compare','Alternatives'],['evidence','Evidence']].map(([key,label])=><button id={'tab-'+key} role="tab" aria-selected={tab===key} aria-controls="result-content" tabIndex={tab===key?0:-1} onKeyDown={e=>{const keys=comparison?['diagnose','compare','evidence']:['diagnose'];let index=keys.indexOf(key);if(e.key==='ArrowRight')index=(index+1)%keys.length;else if(e.key==='ArrowLeft')index=(index+keys.length-1)%keys.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=keys.length-1;else return;e.preventDefault();setTab(keys[index]);document.getElementById('tab-'+keys[index])?.focus()}} key={key} disabled={key!=='diagnose'&&!comparison} className={tab===key?'selected':''} onClick={()=>setTab(key)}>{label}{tab===key&&<motion.span layoutId="tab-underline" transition={{duration:still?0:.25}}/>}</button>)}</div><div id="result-content" role="tabpanel" aria-labelledby={'tab-'+tab}><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:still?0:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:still?0:.2}}>{tab==='diagnose'?<Diagnosis diagnosis={diagnosis} comparison={comparison} still={still}/>:tab==='compare'?<Compare comparison={comparison} runId={runId} downloads={downloads} still={still}/>:<div className="evidence-view"><div className="eyebrow">EXECUTION RECORD</div><h3>Inspect the evidence.</h3><dl><dt>Run ID</dt><dd>{runId}</dd><dt>Request SHA-256</dt><dd>{state.report.request_sha256}</dd></dl><p className="muted">Includes the applied contract, both verifier outputs, cost assumptions and exclusion reasons.</p><pre>{JSON.stringify(state.report,null,2)}</pre></div>}</motion.div></AnimatePresence></div></div>:!busy&&!failed&&<div className="empty-state"><div className="empty-orbits"><i/><i/><i/><span>∴</span></div><span className="eyebrow">NOT RUN / NOTHING ASSUMED</span><h3>Evidence begins with execution.</h3><p>Explore the original branches. Inspect the repair.<br/>Compare the options under one clear contract.</p><div className="empty-key"><span>01 / OBSERVE</span><span>02 / RECOVER</span><span>03 / DECIDE</span></div></div>}
 {busy&&!diagnosis&&!stale&&<div className="running-art" aria-hidden="true"><div className="scan-line"/><div className="running-grid"/><span>READING THE INSTRUMENT</span></div>}
 {isDone&&<section className="downloads"><div><span className="eyebrow">TAKE THE EVIDENCE WITH YOU</span><h3>Ready for your next step.</h3></div><div className="download-actions">{recommendation?.policy&&downloads.includes('circuits/'+recommendation.qasm_file)&&<a className="primary-download" href={'/api/runs/'+runId+'/circuits/'+recommendation.qasm_file} download={recommendation.qasm_file}><Icon name="down"/>Recommended QASM</a>}{['evidence.zip','report.json'].filter(f=>downloads.includes(f)).map(f=><a key={f} href={'/api/runs/'+runId+'/'+f} download={f}><Icon name="down" size={16}/>{f==='evidence.zip'?'All verified circuits + evidence':'Execution report'}</a>)}</div><p className="fine">Numerically verified in the ideal model. Eligibility and verification are separate; inspect the alternatives before using another circuit.</p><span className="run-id mono">RUN / {runId}</span></section>}
 </div></div></section></main>
 <footer><a className="brand" href="#">RetryGuard<span className="brand-mark">/</span></a><p>Every outcome matters.</p><span>LOCAL WORKSPACE · IDEAL MODEL · NO HARDWARE CLAIMS</span></footer></>}
 <AnimatePresence>{info&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setInfo(false)}><HowItWorks close={()=>setInfo(false)} onWorkspace={()=>{setInfo(false);location.hash='workspace'}} still={still} entrance={!entered}/></motion.div>}</AnimatePresence>
 </div></MotionConfig>
}
createRoot(document.getElementById('root')).render(<App/>);
