import React, { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, ArrowUpRight, RotateCcw, X, GitBranch, ShieldCheck } from 'lucide-react';

const chapters = ['Observe', 'Recover', 'Bound', 'Decide'];
const titles = ['A failure is still an operation.', 'Undo the change. Keep the input.', 'A stopping rule needs a contract.', 'A repair is not always the best choice.'];
const descriptions = [
  'Choose an outcome to see why a failure flag alone does not tell you whether your data survived.',
  'Toggle the correction. Even the last failed attempt must return the original input before reporting timeout.',
  'Adjust the attempt cap. More attempts reduce timeout probability, but do not remove the need for recovery.',
  'Change the source constraint. An implementation can be correct and still be ineligible for your task.',
];
const percent = (n: number) => `${Number((100*n).toFixed(6))}%`;
export function HowItWorks({close, onWorkspace, still, entrance}: {close:()=>void; onWorkspace:()=>void; still:boolean; entrance:boolean}) {
  const [step,setStep]=useState(0),[branch,setBranch]=useState<'success'|'failure'>('failure'),[recovery,setRecovery]=useState(false),[cap,setCap]=useState(3),[preserve,setPreserve]=useState(false);
  const dialog=useRef<HTMLElement>(null),heading=useRef<HTMLHeadingElement>(null),mounted=useRef(false);
  useEffect(()=>{
    const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;
    document.body.style.overflow='hidden';dialog.current?.focus();
    const onKey=(e:KeyboardEvent)=>{
      if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();return;}
      if(e.key!=='Tab')return;
      const nodes=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled), a[href], input:not(:disabled), [tabindex="0"]')||[]).filter(n=>n.getClientRects().length);
      const first=nodes[0],last=nodes[nodes.length-1];
      if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current||document.activeElement===heading.current)){e.preventDefault();last?.focus();}
      else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===dialog.current||document.activeElement===heading.current)){e.preventDefault();first?.focus();}
    };
    document.addEventListener('keydown',onKey);
    return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',onKey);if(previous?.isConnected)previous.focus();};
  },[]);
  useEffect(()=>{if(mounted.current)heading.current?.focus();mounted.current=true;},[step]);
  const reset=()=>{setStep(0);setBranch('failure');setRecovery(false);setCap(3);setPreserve(false)};
  return <motion.section ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="tour-title" className="tour-dialog" onClick={e=>e.stopPropagation()} initial={{opacity:0,y:still?0:22}} animate={{opacity:1,y:0}} exit={{opacity:0}}>
    <header className="tour-header"><div><span className="eyebrow">RETRYGUARD / INTERACTIVE FIELD GUIDE</span><span className="tour-disclosure">Illustrative model · no backend run</span></div><button className="tour-close" onClick={close} aria-label="Close walkthrough"><X size={19}/></button></header>
    <nav className="tour-chapters" aria-label="Walkthrough chapters">{chapters.map((label,i)=><button key={label} aria-current={step===i?'step':undefined} className={step===i?'active':''} onClick={()=>setStep(i)}><span>{String(i+1).padStart(2,'0')}</span>{label}{step===i&&<motion.i layoutId="tour-progress" transition={{duration:still?0:.25}}/>}</button>)}</nav>
    <div className="tour-content"><div className="tour-copy"><div className="eyebrow">{String(step+1).padStart(2,'0')} / {chapters[step].toUpperCase()}</div><h2 ref={heading} tabIndex={-1} id="tour-title">{titles[step]}</h2><p>{descriptions[step]}</p></div>
    <AnimatePresence mode="wait"><motion.div key={step} className="tour-experiment" initial={{opacity:0,x:still?0:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:still?0:-8}} transition={{duration:still?0:.18}}>
      {step===0&&<><div className="tour-example-label"><GitBranch size={15}/> TOY TRIAL · INPUT |0⟩ · TARGET H</div><div className="tour-choice" role="group" aria-label="Choose trial outcome"><button aria-pressed={branch==='success'} onClick={()=>setBranch('success')}>Success <small>probability ½</small></button><button aria-pressed={branch==='failure'} onClick={()=>setBranch('failure')}>Failure <small>probability ½</small></button></div><div className="tour-state-flow"><State label="INPUT" value="|0⟩"/><ArrowRight className="flow-arrow"/><div className="tour-operation">{branch==='success'?'H':'X'}<small>{branch==='success'?'intended target':'failure operation'}</small></div><ArrowRight className="flow-arrow"/><State label="ACTUAL OUTPUT" value={branch==='success'?'|+⟩':'|1⟩'} warning={branch==='failure'}/></div><div role="status" className={'tour-finding '+(branch==='failure'?'warn':'ok')}><strong>{branch==='failure'?'Failure changed the input.':'Success applied the target.'}</strong><p>{branch==='failure'?'Stopping now returns |1⟩ instead of |0⟩. A failure label does not restore the data.':'The intended Hadamard operation maps |0⟩ to |+⟩. The successful branch meets this illustrative target.'}</p></div><p className="tour-note">Toy instrument: K₀ = H/√2, K₁ = X/√2. This is an analytic teaching example, not an uploaded circuit or an upstream bug.</p></>}
      {step===1&&<><div className="tour-example-label"><RotateCcw size={15}/> FINAL FAILED ATTEMPT</div><label className="tour-toggle"><span><b>Apply recovery X</b><small>Toggle to compare the returned state</small></span><input type="checkbox" checked={recovery} onChange={e=>setRecovery(e.target.checked)}/></label><div className="tour-state-flow"><State label="AFTER FAILURE" value="|1⟩" warning/><ArrowRight className="flow-arrow"/><div className={'tour-operation '+(recovery?'enabled':'disabled')}>{recovery?'X':'—'}<small>{recovery?'recovery applied':'no recovery'}</small></div><ArrowRight className="flow-arrow"/><State label="RETURNED STATE" value={recovery?'|0⟩':'|1⟩'} warning={!recovery}/></div><div role="status" className={'tour-finding '+(recovery?'ok':'warn')}><strong>{recovery?'Input restored; timeout can be reported.':'Timeout would return the wrong state.'}</strong><p>{recovery?'X reverses the failure operation: X·X = I. The same identity holds for every input, not just |0⟩.':'The retry budget does not excuse an unrecovered final failure. Correct the data before returning timeout.'}</p></div><p className="tour-note">The real analyzer derives a correction for each supported branch. Irreversible information-leaking failures are rejected rather than given a false repair.</p></>}
      {step===2&&<><div className="tour-example-label">INDEPENDENT ATTEMPTS · p = ½ · RECOVER EVERY FAILURE</div><label className="tour-cap" htmlFor="tour-cap">Attempt cap <strong>{cap}</strong></label><input id="tour-cap" type="range" min="1" max="8" value={cap} onChange={e=>setCap(Number(e.target.value))}/><div className="tour-attempts" aria-label={`${cap} maximum attempts`}>{Array.from({length:8},(_,i)=><span key={i} className={i<cap?'available':''}>{i+1}</span>)}</div><div className="tour-probabilities"><div><small>SUCCESS BY CAP</small><strong>{percent(1-Math.pow(.5,cap))}</strong></div><div><small>TIMEOUT</small><strong>{percent(Math.pow(.5,cap))}</strong></div></div><div className="tour-probability-track" role="img" aria-label={`Success ${percent(1-Math.pow(.5,cap))}; timeout ${percent(Math.pow(.5,cap))}`}><motion.span animate={{width:`${100*(1-Math.pow(.5,cap))}%`}} transition={{duration:still?0:.25}}/></div><div role="status" className={'tour-finding '+(cap>=7?'ok':'warn')}><strong>{cap>=7?'Meets an illustrative 1% timeout limit.':'Above an illustrative 1% timeout limit.'}</strong><p>Timeout = (1 − p)<sup>n</sup> = (½)<sup>{cap}</sup>. Stop on the first success; only failed attempts continue.</p></div><p className="tour-note">These percentages are computed from the stated toy model. They are not experimental measurements or verification results. A normalized timeout-state check still matters when timeout is rare.</p></>}
      {step===3&&<><div className="tour-example-label"><ShieldCheck size={15}/> ELIGIBILITY IS NOT VERIFICATION</div><label className="tour-toggle"><span><b>Preserve original trial</b><small>Change what is eligible to be selected</small></span><input type="checkbox" checked={preserve} onChange={e=>setPreserve(e.target.checked)}/></label><div className="tour-alternatives">{[['Repaired source','Original trial plus failure recovery',true],['Fixed retry','Conservative direct replacement',false],['Selected retry','Budget-selected direct replacement',false],['Deterministic','Direct target implementation',false]].map(([name,note,source])=><div className={preserve&&!source?'excluded':''} key={String(name)}><span><b>{name}</b><small>{note}</small></span><span>{preserve&&!source?'Excluded by constraint':'Potentially eligible'}</span></div>)}</div><div className="tour-finding"><strong>{preserve?'Preservation excludes the three replacements.':'All four strategies can be considered.'}</strong><p>No winner is assumed here. A real run verifies candidates, checks the budget, and selects the least-cost eligible implementation under the chosen weights.</p></div><p className="tour-note">Current scope: one data qubit, 1–2 ancillas, ideal U/CX gates. Numerical checks are not a formal proof or hardware certification. Uncontrolled targets are compared under the same final-state contract.</p></>}
    </motion.div></AnimatePresence></div>
    <footer className="tour-footer"><button className="tour-reset" onClick={reset}><RotateCcw size={14}/>Reset guide</button><div className="tour-pagination"><button className="tour-prev" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={15}/>Back</button>{step<3?<button className="tour-next" onClick={()=>setStep(s=>s+1)}>Next: {chapters[step+1]}<ArrowRight size={16}/></button>:<button className="tour-next" onClick={onWorkspace}>Open real workspace<ArrowUpRight size={17}/></button>}</div></footer>
    <button className="tour-return" onClick={close}>{entrance?'Back to entrance':'Back to the workspace'}</button>
  </motion.section>;
}
function State({label,value,warning=false}:{label:string;value:string;warning?:boolean}) { return <div className={'tour-state '+(warning?'warning':'')}><small>{label}</small><strong>{value}</strong></div>; }
